import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Dashboard } from "@/comopnents/dashboard/dashboard";

export default function Home() {
  return (
    <>
      <Head>
        <script
          src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"
          type="text/javascript"
          async
        ></script>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Dashboard />
      </main>
    </>
  );
}
